routes/web.php
        Route::post('appointments/update-status', ['as' => 'appointments.update_status', 'middleware' => ['permission:admin.appointments.status'],  'uses' => 'AppointmentsController@postUpdateStatus']);
        Route::post('appointments/archive/{id}', ['as' => 'appointments.archive', 'middleware' => ['permission:admin.appointments.edit'],  'uses' => 'AppointmentsController@postArchive']);
        Route::post('appointments/unarchive/{id}', ['as' => 'appointments.unarchive', 'middleware' => ['permission:admin.appointments.edit'],  'uses' => 'AppointmentsController@postUnArchive']);


//        Route::get('appointments/permissions/{id}', ['as' => 'appointments.permissions', 'middleware' => ['permission:admin.appointments.permissions'], 'uses' => 'RolesController@getPermissions']);
//        Route::post('appointments/permissions/{id}', ['as' => 'appointments.permissions', 'middleware' => ['permission:admin.appointments.permissions'], 'uses' => 'RolesController@postPermissions']);

/*
        // Appointments ROUTE
        Route::get('appointments', ['as' => 'appointments.view',  'uses' => 'AppointmentsController@getIndex']);
        Route::get('appointments/list', ['as' => 'appointments.list', 'uses' => 'AppointmentsController@getList']);
        Route::get('appointments/add', ['as' => 'appointments.add', 'uses' => 'AppointmentsController@getAdd']);
        Route::post('appointments/add', ['as' => 'appointments.add', 'uses' => 'AppointmentsController@postAdd']);
        Route::get('appointments/edit/{id}', ['as' => 'appointments.edit', 'uses' => 'AppointmentsController@getEdit']);
        Route::post('appointments/edit/{id}', ['as' => 'appointments.edit', 'uses' => 'AppointmentsController@postEdit']);
        Route::get('appointments/delete/{id}', ['as' => 'appointments.delete', 'uses' => 'AppointmentsController@getDelete']);
        Route::get('appointments/details/{id}', ['as' => 'appointments.details', 'uses' => 'AppointmentsController@getDetails']);
        Route::get('appointments/index', 'AppointmentsController@index')->name('index');
        Route::get('appointments/create', 'AppointmentsController@create')->name('create');
        Route::post('appointments/store', 'AppointmentsController@store')->name('store');
        Route::get('appointments/edit/{id}', 'AppointmentsController@edit')->name('edit');
        Route::put('appointments/update/{id}', 'AppointmentsController@update')->name('update');
        Route::delete('appointment/{id}','AppointmentsController@delete')->name('delete');
        Route::get('appointment/search','AppointmentsController@search')->name('search');
*/

        // Employees ROUTE
        Route::get('employees', ['as' => 'employees.view', 'middleware' => ['permission:admin.employees.view|admin.employees.add|admin.employees.edit|admin.employees.delete|admin.employees.status|admin.employees.permissions'], 'uses' => 'EmployeesController@getIndex']);
        Route::get('employees/list', ['as' => 'employees.list', 'middleware' => ['permission:admin.employees.view|admin.employees.add|admin.employees.edit|admin.employees.delete|admin.employees.status|admin.employees.permissions'], 'uses' => 'EmployeesController@getList']);
        Route::get('employees/add', ['as' => 'employees.add', 'middleware' => ['permission:admin.employees.add'], 'uses' => 'EmployeesController@getAdd']);
        Route::post('employees/add', ['as' => 'employees.add', 'middleware' => ['permission:admin.employees.add'], 'uses' => 'EmployeesController@postAdd']);
        Route::get('employees/edit/{id}', ['as' => 'employees.edit', 'middleware' => ['permission:admin.employees.edit'], 'uses' => 'EmployeesController@getEdit']);
        Route::post('employees/edit/{id}', ['as' => 'employees.edit', 'middleware' => ['permission:admin.employees.edit'], 'uses' => 'EmployeesController@postEdit']);
        Route::get('employees/delete/{id}', ['as' => 'employees.delete', 'middleware' => ['permission:admin.employees.delete'], 'uses' => 'EmployeesController@getDelete']);

        // BusinessSchedule ROUTE
        Route::get('business_schedules', ['as' => 'business_schedules.view', 'middleware' => ['permission:admin.business_schedules.view|admin.business_schedules.add|admin.business_schedules.edit|admin.business_schedules.delete|admin.business_schedules.status|admin.business_schedules.permissions'], 'uses' => 'BusinessScheduleController@getIndex']);
        Route::get('business_schedules/list', ['as' => 'business_schedules.list', 'middleware' => ['permission:admin.business_schedules.view|admin.business_schedules.add|admin.business_schedules.edit|admin.business_schedules.delete|admin.business_schedules.status|admin.business_schedules.permissions'], 'uses' => 'BusinessScheduleController@getList']);
        Route::get('business_schedules/add', ['as' => 'business_schedules.add', 'middleware' => ['permission:admin.business_schedules.add'], 'uses' => 'BusinessScheduleController@getAdd']);
        Route::post('business_schedules/add', ['as' => 'business_schedules.add', 'middleware' => ['permission:admin.business_schedules.add'], 'uses' => 'BusinessScheduleController@postAdd']);
        Route::get('business_schedules/edit/{id}', ['as' => 'business_schedules.edit', 'middleware' => ['permission:admin.business_schedules.edit'], 'uses' => 'BusinessScheduleController@getEdit']);
        Route::post('business_schedules/edit/{id}', ['as' => 'business_schedules.edit', 'middleware' => ['permission:admin.business_schedules.edit'], 'uses' => 'BusinessScheduleController@postEdit']);
        Route::get('business_schedules/delete/{id}', ['as' => 'business_schedules.delete', 'middleware' => ['permission:admin.business_schedules.delete'], 'uses' => 'BusinessScheduleController@getDelete']);
        Route::get('business_schedules/order', ['as' => 'business_schedules.order', 'middleware' => ['permission:admin.business_schedules.order'], 'uses' => 'BusinessScheduleController@getOrder']);
        Route::post('business_schedules/order', ['as' => 'business_schedules.order', 'middleware' => ['permission:admin.business_schedules.order'], 'uses' => 'BusinessScheduleController@postOrder']);
        Route::post('business_schedules/upload/{id?}', ['as' => 'business_schedules.upload', 'middleware' => ['permission:admin.business_schedules.order'], 'uses' => 'BusinessScheduleController@postUpload']);
        Route::post('business_schedules/upload-single/{id}', ['as' => 'business_schedules.upload_single', 'middleware' => ['permission:admin.business_schedules.order'], 'uses' => 'BusinessScheduleController@postUploadSingleImage']);
        Route::post('business_schedules/attachment/delete/{id}', ['as' => 'albums.delete_attachment', 'middleware' => ['permission:admin.business_schedules.order'] , 'uses' => 'BusinessScheduleController@postAttachmentDelete']);

        // Employees ROUTE
//        Route::get('employees', ['as' => 'employees.view',  'uses' => 'EmployeesController@getIndex']);
//        Route::get('employees/list', ['as' => 'employees.list', 'uses' => 'EmployeesController@getList']);
//        Route::get('employees/add', ['as' => 'employees.add', 'uses' => 'EmployeesController@getAdd']);
//        Route::post('employees/add', ['as' => 'employees.add', 'uses' => 'EmployeesController@postAdd']);
//        Route::get('employees/edit/{id}', ['as' => 'employees.edit', 'uses' => 'EmployeesController@getEdit']);
//        Route::post('employees/edit/{id}', ['as' => 'employees.edit', 'uses' => 'EmployeesController@postEdit']);
//        Route::get('employees/delete/{id}', ['as' => 'employees.delete', 'uses' => 'EmployeesController@getDelete']);
//        Route::get('employees/details/{id}', ['as' => 'employees.details', 'uses' => 'EmployeesController@getDetails']);
        // Tasks ROUTE
        Route::get('tasks', ['as' => 'tasks.view', 'middleware' => ['permission:admin.tasks.view'],  'uses' => 'TasksController@getIndex']);
        Route::get('tasks/archive', ['as' => 'tasks.archive', 'middleware' => ['permission:admin.tasks.view'],  'uses' => 'TasksController@getArchive']);
        Route::get('tasks/list', ['as' => 'tasks.list', 'middleware' => ['permission:admin.tasks.view'], 'uses' => 'TasksController@getList']);
        Route::get('tasks/list-archive', ['as' => 'tasks.list-archive', 'middleware' => ['permission:admin.tasks.archive'], 'uses' => 'TasksController@getArchiveList']);
        Route::get('tasks/add', ['as' => 'tasks.add', 'middleware' => ['permission:admin.tasks.add'], 'uses' => 'TasksController@getAdd']);
        Route::post('tasks/add', ['as' => 'tasks.add', 'middleware' => ['permission:admin.tasks.add'], 'uses' => 'TasksController@postAdd']);
        Route::get('tasks/edit/{id}', ['as' => 'tasks.edit', 'middleware' => ['permission:admin.tasks.edit'], 'uses' => 'TasksController@getEdit']);
        Route::post('tasks/edit/{id}', ['as' => 'tasks.edit', 'middleware' => ['permission:admin.tasks.edit'], 'uses' => 'TasksController@postEdit']);
        Route::get('tasks/delete/{id}', ['as' => 'tasks.delete', 'middleware' => ['permission:admin.tasks.delete'], 'uses' => 'TasksController@getDelete']);
        Route::get('tasks/details/{id}', ['as' => 'tasks.details', 'middleware' => ['permission:admin.tasks.details'], 'uses' => 'TasksController@getDetails']);
        Route::post('tasks/update-status', ['as' => 'tasks.update_status', 'middleware' => ['permission:admin.tasks.update_status'], 'uses' => 'TasksController@postUpdateStatus']);
        //Logout Route
        Route::get('logout', ['as' => 'dashboard.logout', 'uses' => 'DashboardController@getLogout']);
    });
});
//Route::get('admin/newappointment', 'Admin\AppointmentsController@index')->name('index');
//Route::post('admin/newappointment', 'Admin\AppointmentsController@store')->name('store');


//Dictionary Route
Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::get('dictionary.js', function () {

app/Models/BaseModel.php
<?php
/**
 * Created by PhpStorm.
 * User: Redwan-PC
 * Date: 12/16/2018
 * Time: 3:30 PM
 */

namespace App\Models;

use App\Traits\EncryptionTrait;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class BaseModel extends Model
{
    use EncryptionTrait;

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
    }

    function getIdHashAttribute()
    {
        return $this->encrypt($this->id);
    }
    /////////////////////////////////////////////////////////
    public function getHumansDateAttribute()
    {
        return Carbon::parse($this->created_at)->diffForHumans();
    }
    public static function getHumansDate($created_at)
    {
        return Carbon::parse($created_at)->diffForHumans();
    }
    /////////////////////////////////////////
    public static function getArabicMonth($date)
    {
        $months = [
            "Jan" => "يناير",
            "Feb" => "فبراير",
            "Mar" => "مارس",
            "Apr" => "ابريل",
            "May" => "مايو",
            "Jun" => "يونيو",
            "Jul" => "يوليو",
            "Aug" => "أغسطس",
            "Sep" => "سبتمبر",
            "Oct" => "أكتوبر",
            "Nov" => "نوفمبر",
            "Dec" => "ديسمبر"
        ];

        $month = date("M", strtotime($date));

        $month = $months[$month];
        return $month;
    }
}

app/Models/Task.php
<?php

namespace App\Models;

use App\Traits\EncryptionTrait;
use Illuminate\Database\Eloquent\Model;

class Task extends BaseModel
{
    use EncryptionTrait;
    protected $table = "tasks";
    protected $fillable = ['name', 'status'];
    public function employees()
    {
        return $this->belongsToMany('App\Models\Employee', 'task_employees', 'task_id', 'employee_id');
    }
}

resources/views/admin/tasks/add.blade.php
@extends('admin.layout.master')

@section('title')
    إضافة مهمة
@stop

@section('css')

@stop

@section('subheader')
    <div class="kt-subheader   kt-grid__item" id="kt_subheader">
        <div class="kt-container  kt-container--fluid ">
            <div class="kt-subheader__main">
                <h3 class="kt-subheader__title">
                    وزارة الأوقاف والشؤون الدينية </h3>
                <span class="kt-subheader__separator kt-hidden"></span>
                <div class="kt-subheader__breadcrumbs">
                    <a href="{{ route('admin.dashboard.view') }}" class="kt-subheader__breadcrumbs-home"><i
                            class="flaticon2-shelter"></i></a>
                    <span class="kt-subheader__breadcrumbs-separator"></span>
                    <a href="{{ route('admin.dashboard.view') }}" class="kt-subheader__breadcrumbs-link">
                        الرئيسية
                    </a>
                    <span class="kt-subheader__breadcrumbs-separator"></span>
                    <a href="{{ route('admin.tasks.view') }}" class="kt-subheader__breadcrumbs-link">
                        المهام
                    </a>
                    <span class="kt-subheader__breadcrumbs-separator"></span>
                    <a href="{{ route('admin.tasks.add') }}" class="kt-subheader__breadcrumbs-link">
                        إضافة مهمة
                    </a>
                </div>
            </div>
        </div>
    </div>
@stop

@section('content')
    <!-- begin:: Content -->
    <div class="row">
        <div class="col-lg-12">
            <!--begin::Portlet-->
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            إضافة موظف
                        </h3>
                    </div>
                </div>
                <!--begin::Form-->
                <form class="kt-form kt-form--label-right" id="frmAdd" method="post"
                      action="{{ route('admin.tasks.add') }}">
                    <div class="kt-portlet__body">
                        <div class="form-group row">
                            <div class="col-lg-6">
                                <label class="">المهمة:</label>
                                <input type="text" class="form-control" name="name" value="{{ old('name') }}"
                                       placeholder="المهمة">
                            </div>
                            <div class="col-lg-6">
                                <label class="">الحالة:</label>
                                <select class="form-control kt-selectpicker" name="status" data-live-search="true">
                                    @foreach($task_status as $k => $item)
                                        <option value="{{ $k }}">{{ $item }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-lg-6">
                                <label class="">المكلف بها:</label>
                                <select class="form-control kt-selectpicker" name="employees[]" data-live-search="true" multiple>
                                    @foreach($employees as $k => $item)
                                        <option value="{{ $item->id }}">{{ $item->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="kt-portlet__foot">
                        <div class="kt-form__actions">
                            <div class="row">
                                <div class="col-lg-6 kt-align-right">
                                    <button type="submit" class="btn btn-brand save">حفظ</button>
                                    <a href="{{ route('admin.tasks.view') }}" class="btn btn-secondary">الغاء</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <!--end::Form-->
            </div>
            <!--end::Portlet-->
        </div>
    </div>
    <!-- End:: Content -->
@stop

@section('js')
    <script src="assets/admin/general/js/scripts/tasks.js" type="text/javascript"></script>
@stop

resources/views/admin/tasks/archive.blade.php
@extends('admin.layout.master')

@section('title')
    الرئيسية
@stop

@section('css')

@stop
@section('subheader')
    <div class="kt-subheader   kt-grid__item" id="kt_subheader">
        <div class="kt-container  kt-container--fluid ">
            <div class="kt-subheader__main">
                <h3 class="kt-subheader__title">
                    وزارة الأوقاف والشؤون الدينية </h3>
                <span class="kt-subheader__separator kt-hidden"></span>
                <div class="kt-subheader__breadcrumbs">
                    <a href="{{ route('admin.dashboard.view') }}" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
                    <span class="kt-subheader__breadcrumbs-separator"></span>
                    <a href="{{ route('admin.dashboard.view') }}" class="kt-subheader__breadcrumbs-link">
                        الرئيسية </a>
                    <span class="kt-subheader__breadcrumbs-separator"></span>
                    <a href="{{ route('admin.tasks.view') }}" class="kt-subheader__breadcrumbs-link">
                        فريق مكتب الوكيل </a>
                </div>
            </div>
        </div>
    </div>
@stop

@section('content')
    <!-- begin:: Content -->
        <div class="row">
            <div class="col-lg-12">
                <!--begin::Portlet-->
                <div class="kt-portlet">
                    <div class="kt-portlet__head">
                        <div class="kt-portlet__head-label">
                            <h3 class="kt-portlet__head-title">
                                البحث
                            </h3>
                        </div>
                    </div>
                    <!--begin::Form-->
                    <form class="kt-form kt-form--label-right">
                        <div class="kt-portlet__body">
                            <div class="form-group row">
                                <div class="col-lg-6">
                                    <input type="email" class="form-control searchable" id="name" name="name" placeholder="اسم المجموعة">
                                </div>
                            </div>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
                <!--end::Portlet-->
            </div>
        </div>
    <!-- End:: Content -->

    <!-- begin:: Content -->
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
            <div class="kt-portlet__head-label">
                <h3 class="kt-portlet__head-title">
                    إدارة فريق مكتب الوكيل
                </h3>
            </div>
{{--            @can('admin.tasks.add')--}}
                <div class="kt-portlet__head-toolbar">
                    <div class="kt-portlet__head-wrapper">
                        <div class="kt-portlet__head-actions">
                            <a href="{{ route('admin.tasks.add') }}" class="btn btn-brand btn-elevate btn-icon-sm">
                                إضافة جديد
                            </a>
                        </div>
                    </div>
                </div>
{{--            @endcan--}}
        </div>
        <div class="kt-portlet__body">
            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover" id="tasks_archive_table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>المهمة</th>
                    <th>المكلف بها</th>
                    <th>حالة المهمة</th>
                    <th>أدوات</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>

            <!--end: Datatable -->
        </div>
    </div>
    <!-- end:: Content -->
@stop

@section('js')
    <script src="assets/admin/general/js/scripts/tasks.js" type="text/javascript"></script>
@stop

resources/views/admin/tasks/edit.blade.php
@extends('admin.layout.master')

@section('title')
    تعديل موظف
@stop

@section('css')

@stop

@section('subheader')
    <div class="kt-subheader   kt-grid__item" id="kt_subheader">
        <div class="kt-container  kt-container--fluid ">
            <div class="kt-subheader__main">
                <h3 class="kt-subheader__title">
                    وزارة الأوقاف والشؤون الدينية </h3>
                <span class="kt-subheader__separator kt-hidden"></span>
                <div class="kt-subheader__breadcrumbs">
                    <a href="{{ route('admin.dashboard.view') }}" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
                    <span class="kt-subheader__breadcrumbs-separator"></span>
                    <a href="{{ route('admin.dashboard.view') }}" class="kt-subheader__breadcrumbs-link">
                        الرئيسية
                    </a>
                    <span class="kt-subheader__breadcrumbs-separator"></span>
                    <a href="{{ route('admin.tasks.view') }}" class="kt-subheader__breadcrumbs-link">
                        الموظفين
                    </a>
                    <span class="kt-subheader__breadcrumbs-separator"></span>
                    <a href="{{ route('admin.tasks.edit', ['id' => $info->id_hash]) }}" class="kt-subheader__breadcrumbs-link">
                        تعديل موظف
                    </a>
                </div>
            </div>
        </div>
    </div>
@stop


@section('content')
    <!-- begin:: Content -->
    <div class="row">
        <div class="col-lg-12">
            <!--begin::Portlet-->
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            تعديل موظف
                        </h3>
                    </div>
                </div>
                <!--begin::Form-->
                <form class="kt-form kt-form--label-right" id="frmEdit" method="post" action="{{ route('admin.tasks.edit', ['id' => $info->id_hash]) }}">
                    <div class="kt-portlet__body">
                        <div class="form-group row">
                            <div class="col-lg-6">
                                <label class="">اسم الموظف:</label>
                                <input type="text" class="form-control" name="name" value="{{ $info->name }}" placeholder="اسم الموظف">
                            </div>
                            <div class="col-lg-6">
                                <label class="">الحالة:</label>
                                <select class="form-control kt-selectpicker" name="status" data-live-search="true">
                                    @foreach($task_status as $k => $item)
                                        <option {{ $info->status == $k ? "selected" : "" }} value="{{ $k }}">{{ $item }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-lg-6">
                                <label class="">المكلف بها:</label>
                                <select class="form-control kt-selectpicker" name="employees[]" data-live-search="true" multiple>
                                    @foreach($employees as $k => $item)
                                        <option value="{{ $item->id }}" {{ in_array($item->id,array_column(array_column($info->employees->toArray(),'pivot'),'employee_id')) ? 'selected' : '' }}>{{ $item->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="kt-portlet__foot">
                        <div class="kt-form__actions">
                            <div class="row">
                                <div class="col-lg-6 kt-align-right">
                                    <button type="submit" class="btn btn-brand save">حفظ التغييرات</button>
                                    <a href="{{ route('admin.tasks.view') }}" class="btn btn-secondary">الغاء</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <!--end::Form-->
            </div>
            <!--end::Portlet-->
        </div>
    </div>
    <!-- End:: Content -->
@stop

@section('js')
    <script src="assets/admin/general/js/scripts/tasks.js" type="text/javascript"></script>
@stop

resources/views/admin/tasks/view.blade.php
@extends('admin.layout.master')

@section('title')
    الرئيسية
@stop

@section('css')

@stop
@section('subheader')
    <div class="kt-subheader   kt-grid__item" id="kt_subheader">
        <div class="kt-container  kt-container--fluid ">
            <div class="kt-subheader__main">
                <h3 class="kt-subheader__title">
                    وزارة الأوقاف والشؤون الدينية </h3>
                <span class="kt-subheader__separator kt-hidden"></span>
                <div class="kt-subheader__breadcrumbs">
                    <a href="{{ route('admin.dashboard.view') }}" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
                    <span class="kt-subheader__breadcrumbs-separator"></span>
                    <a href="{{ route('admin.dashboard.view') }}" class="kt-subheader__breadcrumbs-link">
                        الرئيسية </a>
                    <span class="kt-subheader__breadcrumbs-separator"></span>
                    <a href="{{ route('admin.tasks.view') }}" class="kt-subheader__breadcrumbs-link">
                        فريق مكتب الوكيل </a>
                </div>
            </div>
        </div>
    </div>
@stop

@section('content')
    <!-- begin:: Content -->
        <div class="row">
            <div class="col-lg-12">
                <!--begin::Portlet-->
                <div class="kt-portlet">
                    <div class="kt-portlet__head">
                        <div class="kt-portlet__head-label">
                            <h3 class="kt-portlet__head-title">
                                البحث
                            </h3>
                        </div>
                    </div>
                    <!--begin::Form-->
                    <form class="kt-form kt-form--label-right">
                        <div class="kt-portlet__body">
                            <div class="form-group row">
                                <div class="col-lg-6">
                                    <input type="email" class="form-control searchable" id="name" name="name" placeholder="اسم المجموعة">
                                </div>
                            </div>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
                <!--end::Portlet-->
            </div>
        </div>
    <!-- End:: Content -->

    <!-- begin:: Content -->
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
            <div class="kt-portlet__head-label">
                <h3 class="kt-portlet__head-title">
                    إدارة فريق مكتب الوكيل
                </h3>
            </div>
{{--            @can('admin.tasks.add')--}}
                <div class="kt-portlet__head-toolbar">
                    <div class="kt-portlet__head-wrapper">
                        <div class="kt-portlet__head-actions">
                            <a href="{{ route('admin.tasks.add') }}" class="btn btn-brand btn-elevate btn-icon-sm">
                                إضافة جديد
                            </a>
                        </div>
                    </div>
                </div>
{{--            @endcan--}}
        </div>
        <div class="kt-portlet__body">
            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover" id="tasks_table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>المهمة</th>
                    <th>المكلف بها</th>
                    <th>حالة المهمة</th>
                    <th>أدوات</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>

            <!--end: Datatable -->
        </div>
    </div>
    <!-- end:: Content -->
@stop

@section('js')
    <script src="assets/admin/general/js/scripts/tasks.js" type="text/javascript"></script>
@stop