routes/web.php
<?php

use App\Http\Controllers\Admin\appointmentController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('admin/dashboard');
});
Route::get('admin', function () {
    return redirect('admin/dashboard');
});

Route::get('/clear', function () {
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    Cache::forget('spatie.permission.cache');
    return 'cleared';
});
Route::name('admin.')->group(function () {
    //LOGIN GROUP
    Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['guest:admin', 'throttle:100,1']], function () {
        //LOGIN ROUTE
        Route::get('login', ['as' => 'login.view', 'uses' => 'LoginController@getLogin']);
        Route::post('login', ['as' => 'login.view', 'uses' => 'LoginController@postLogin']);
    });

    Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['web', 'auth:admin', 'throttle:100,1']], function () {
        Route::get('test', ['as' => 'test', 'uses' => 'TestController@getIndex']);

        //Route::get('newappointment', ['as' => 'newappointment.view', 'uses' => 'AppointmentsController@index']);

        //Route::get('appointment', ['as' => 'appointment.view', 'uses' => 'NewAppointmentController@index']);
        //my route
        //Route::get('newappointment', ['as' => 'newappointment.view', 'uses' => 'AppointmentsController@create']);
        //Route::post('newappointment', ['as' => 'newappointment.view', 'uses' => 'AppointmentsController@store'])->name('store');
        /*Route::get('newappointment/{id}', ['as' => 'newappointment.view', 'uses' => 'AppointmentsController@edit']);
        Route::put('newappointment/{id}', ['as' => 'newappointment.view', 'uses' => 'AppointmentsController@update']);
        Route::delete('newappointment/{id}', ['as' => 'newappointment.view', 'uses' => 'AppointmentsController@delete']);*/

        //Dashboard Route
        Route::get('dashboard', ['as' => 'dashboard.view', 'uses' => 'DashboardController@getIndex']);
        Route::get('profile', ['as' => 'dashboard.profile', 'uses' => 'DashboardController@getProfile']);
        Route::post('profile', ['as' => 'dashboard.profile', 'uses' => 'DashboardController@postProfile']);
        Route::get('password', ['as' => 'dashboard.password', 'uses' => 'DashboardController@getPassword']);
        Route::post('password', ['as' => 'dashboard.password', 'uses' => 'DashboardController@postPassword']);

        //Setting Route
        //        Route::get('settings', ['as' => 'settings.view', 'middleware' => ['permission:admin.settings.view'], 'uses' => 'SettingsController@getIndex']);
        //        Route::post('settings', ['as' => 'settings.view', 'middleware' => ['permission:admin.settings.view'], 'uses' => 'SettingsController@postIndex']);
        //
        //Users Route
        Route::get('users', ['as' => 'users.view', 'middleware' => ['permission:admin.users.view|admin.users.add|admin.users.edit|admin.users.delete|admin.users.password'], 'uses' => 'UsersController@getIndex']);
        Route::get('users/list', ['as' => 'users.list', 'middleware' => ['permission:admin.users.view|admin.users.add|admin.users.edit|admin.users.delete|admin.users.password'], 'uses' => 'UsersController@getList']);
        Route::get('users/add', ['as' => 'users.add', 'middleware' => ['permission:admin.users.add'], 'uses' => 'UsersController@getAdd']);
        Route::post('users/add', ['as' => 'users.add', 'middleware' => ['permission:admin.users.add'], 'uses' => 'UsersController@postAdd']);
        Route::get('users/edit/{id}', ['as' => 'users.edit', 'middleware' => ['permission:admin.users.edit'], 'uses' => 'UsersController@getEdit']);
        Route::post('users/edit/{id}', ['as' => 'users.edit', 'middleware' => ['permission:admin.users.edit'], 'uses' => 'UsersController@postEdit']);
        Route::get('users/password/{id}', ['as' => 'users.password', 'middleware' => ['permission:admin.users.password'], 'uses' => 'UsersController@getPassword']);
        Route::post('users/password/{id}', ['as' => 'users.password', 'middleware' => ['permission:admin.users.password'], 'uses' => 'UsersController@postPassword']);
        Route::get('users/delete/{id}', ['as' => 'users.delete', 'middleware' => ['permission:admin.users.delete'], 'uses' => 'UsersController@getDelete']);
        Route::get('users/permissions/{id}', ['as' => 'users.permissions', 'middleware' => ['permission:admin.users.permissions'], 'uses' => 'UsersController@getPermissions']);
        Route::post('users/permissions/{id}', ['as' => 'users.permissions', 'middleware' => ['permission:admin.users.permissions'], 'uses' => 'UsersController@postPermissions']);


        // ROLES ROUTE
        Route::get('roles', ['as' => 'roles.view', 'middleware' => ['permission:admin.roles.view|admin.roles.add|admin.roles.edit|admin.roles.delete|admin.roles.status|admin.roles.permissions'], 'uses' => 'RolesController@getIndex']);
        Route::get('roles/list', ['as' => 'roles.list', 'middleware' => ['permission:admin.roles.view|admin.roles.add|admin.roles.edit|admin.roles.delete|admin.roles.status|admin.roles.permissions'], 'uses' => 'RolesController@getList']);
        Route::get('roles/add', ['as' => 'roles.add', 'middleware' => ['permission:admin.roles.add'], 'uses' => 'RolesController@getAdd']);
        Route::post('roles/add', ['as' => 'roles.add', 'middleware' => ['permission:admin.roles.add'], 'uses' => 'RolesController@postAdd']);
        Route::get('roles/edit/{id}', ['as' => 'roles.edit', 'middleware' => ['permission:admin.roles.edit'], 'uses' => 'RolesController@getEdit']);
        Route::post('roles/edit/{id}', ['as' => 'roles.edit', 'middleware' => ['permission:admin.roles.edit'], 'uses' => 'RolesController@postEdit']);
        Route::get('roles/delete/{id}', ['as' => 'roles.delete', 'middleware' => ['permission:admin.roles.delete'], 'uses' => 'RolesController@getDelete']);
        Route::post('roles/status', ['as' => 'roles.status', 'middleware' => ['permission:admin.roles.status'], 'uses' => 'RolesController@postStatus']);
        Route::get('roles/permissions/{id}', ['as' => 'roles.permissions', 'middleware' => ['permission:admin.roles.permissions'], 'uses' => 'RolesController@getPermissions']);
        Route::post('roles/permissions/{id}', ['as' => 'roles.permissions', 'middleware' => ['permission:admin.roles.permissions'], 'uses' => 'RolesController@postPermissions']);


        // ROLES ROUTE
        /*
        Route::get('appointments', ['as' => 'appointments.view', 'uses' => 'AppointmentsController@getIndex']);
        Route::get('appointments/list', ['as' => 'appointments.list', 'uses' => 'AppointmentsController@getList']);
        Route::get('appointments/add', ['as' => 'appointments.add', 'uses' => 'AppointmentsController@getAdd']);
        Route::post('appointments/add', ['as' => 'appointments.add', 'uses' => 'AppointmentsController@postAdd']);
        Route::get('appointments/edit/{id}', ['as' => 'appointments.edit', 'uses' => 'AppointmentsController@getEdit']);
        Route::post('appointments/edit/{id}', ['as' => 'appointments.edit', 'uses' => 'AppointmentsController@postEdit']);
        Route::get('appointments/delete/{id}', ['as' => 'appointments.delete', 'uses' => 'AppointmentsController@getDelete']);
        Route::get('appointments/details/{id}', ['as' => 'appointments.details', 'uses' => 'AppointmentsController@getDelete']);
        Route::post('appointments/status', ['as' => 'appointments.status', 'uses' => 'AppointmentsController@getDetails']);*/

        Route::get('appointments', ['as' => 'appointments.view', 'middleware' => ['permission:admin.appointments.view|admin.appointments.add|admin.appointments.edit|admin.appointments.delete|admin.appointments.status'], 'uses' => 'AppointmentsController@getIndex']);
        Route::get('appointments/archived', ['as' => 'appointments.archived.view', 'middleware' => ['permission:admin.appointments.view|admin.appointments.add|admin.appointments.edit|admin.appointments.delete|admin.appointments.status'], 'uses' => 'AppointmentsController@getArchived']);
        Route::get('appointments/list', ['as' => 'appointments.list', 'middleware' => ['permission:admin.appointments.view|admin.appointments.add|admin.appointments.edit|admin.appointments.delete|admin.appointments.status'], 'uses' => 'AppointmentsController@getList']);
        Route::get('appointments/add', ['as' => 'appointments.add', 'middleware' => ['permission:admin.appointments.add'], 'uses' => 'AppointmentsController@getAdd']);
        Route::get('appointments/create', ['as' => 'appointments.add', 'middleware' => ['permission:admin.appointments.add'], 'uses' => 'AppointmentsController@create']);
        Route::post('appointments/add', ['as' => 'appointments.add', 'middleware' => ['permission:admin.appointments.add'], 'uses' => 'AppointmentsController@store']);
        Route::post('appointments/store', ['as' => 'appointments.add', 'middleware' => ['permission:admin.appointments.add'], 'uses' => 'AppointmentsController@store'])->name('store');;
        Route::get('appointments/edit/{id}', ['as' => 'appointments.edit', 'middleware' => ['permission:admin.appointments.edit'], 'uses' => 'AppointmentsController@edit'])->name('edit');
        Route::put('appointments/edit/{id}', ['as' => 'appointments.edit', 'middleware' => ['permission:admin.appointments.edit'], 'uses' => 'AppointmentsController@update']);

resources/views/admin/layout/aside.blade.php
<!-- begin:: Aside -->
{{--<button class="kt-aside-close " id="kt_aside_close_btn"><i class="la la-close"></i></button>--}}
<div class="kt-aside  kt-aside--fixed  kt-grid__item kt-grid kt-grid--desktop kt-grid--hor-desktop" id="kt_aside">

    <!-- begin:: Aside -->
    <div class="kt-aside__brand kt-grid__item " id="kt_aside_brand">
        <div class="kt-aside__brand-logo">
            <a href="{{ route('admin.dashboard.view') }}">
                <img alt="Logo" src="uploads/admin/logo/logo.png" style="max-height: 60px;margin-top: 35px;"/>
            </a>
        </div>
        <div class="kt-aside__brand-tools">
            <button class="kt-aside__brand-aside-toggler" id="kt_aside_toggler">
                <span>
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <polygon id="Shape" points="0 0 24 0 24 24 0 24" />
                            <path d="M5.29288961,6.70710318 C4.90236532,6.31657888 4.90236532,5.68341391 5.29288961,5.29288961 C5.68341391,4.90236532 6.31657888,4.90236532 6.70710318,5.29288961 L12.7071032,11.2928896 C13.0856821,11.6714686 13.0989277,12.281055 12.7371505,12.675721 L7.23715054,18.675721 C6.86395813,19.08284 6.23139076,19.1103429 5.82427177,18.7371505 C5.41715278,18.3639581 5.38964985,17.7313908 5.76284226,17.3242718 L10.6158586,12.0300721 L5.29288961,6.70710318 Z" id="Path-94" fill="#000000" fill-rule="nonzero" transform="translate(8.999997, 11.999999) scale(-1, 1) translate(-8.999997, -11.999999) " />
                            <path d="M10.7071009,15.7071068 C10.3165766,16.0976311 9.68341162,16.0976311 9.29288733,15.7071068 C8.90236304,15.3165825 8.90236304,14.6834175 9.29288733,14.2928932 L15.2928873,8.29289322 C15.6714663,7.91431428 16.2810527,7.90106866 16.6757187,8.26284586 L22.6757187,13.7628459 C23.0828377,14.1360383 23.1103407,14.7686056 22.7371482,15.1757246 C22.3639558,15.5828436 21.7313885,15.6103465 21.3242695,15.2371541 L16.0300699,10.3841378 L10.7071009,15.7071068 Z" id="Path-94" fill="#000000" fill-rule="nonzero" opacity="0.3" transform="translate(15.999997, 11.999999) scale(-1, 1) rotate(-270.000000) translate(-15.999997, -11.999999) " />
                        </g>
                    </svg>
                </span>
                <span>
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <polygon id="Shape" points="0 0 24 0 24 24 0 24" />
                            <path d="M12.2928955,6.70710318 C11.9023712,6.31657888 11.9023712,5.68341391 12.2928955,5.29288961 C12.6834198,4.90236532 13.3165848,4.90236532 13.7071091,5.29288961 L19.7071091,11.2928896 C20.085688,11.6714686 20.0989336,12.281055 19.7371564,12.675721 L14.2371564,18.675721 C13.863964,19.08284 13.2313966,19.1103429 12.8242777,18.7371505 C12.4171587,18.3639581 12.3896557,17.7313908 12.7628481,17.3242718 L17.6158645,12.0300721 L12.2928955,6.70710318 Z" id="Path-94" fill="#000000" fill-rule="nonzero" />
                            <path d="M3.70710678,15.7071068 C3.31658249,16.0976311 2.68341751,16.0976311 2.29289322,15.7071068 C1.90236893,15.3165825 1.90236893,14.6834175 2.29289322,14.2928932 L8.29289322,8.29289322 C8.67147216,7.91431428 9.28105859,7.90106866 9.67572463,8.26284586 L15.6757246,13.7628459 C16.0828436,14.1360383 16.1103465,14.7686056 15.7371541,15.1757246 C15.3639617,15.5828436 14.7313944,15.6103465 14.3242754,15.2371541 L9.03007575,10.3841378 L3.70710678,15.7071068 Z" id="Path-94" fill="#000000" fill-rule="nonzero" opacity="0.3" transform="translate(9.000003, 11.999999) rotate(-270.000000) translate(-9.000003, -11.999999) " />
                        </g>
                    </svg>
                </span>
            </button>
        </div>
    </div>

    <!-- end:: Aside -->

    <!-- begin:: Aside Menu -->
@include("admin.layout.sidebar")


<!-- end:: Aside Menu -->
</div>

<!-- end:: Aside -->

resources/views/admin/layout/delete.blade.php
<div class="modal fade" id="confirm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title m--font-danger" id="exampleModalLabel">
                    {{ trans('delete.caution') }}!
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">
                        &times;
                    </span>
                </button>
            </div>
            <div class="modal-body">
                <h5>
                    {{ trans('delete.message') }}
                </h5>
                <p class="m--font-danger">
                    <strong>{{ trans('delete.note') }},</strong>
                    {{ trans('delete.noteDescription') }}
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    {{ trans('delete.close') }}
                </button>
                <button href="" data-dismiss="modal" aria-hidden="true" class="btn btn-danger delete">
                    {{ trans('delete.yes') }}, ..
                </button>
                <input type="hidden" id="delete_id">
            </div>
        </div>
    </div>
</div>

resources/views/admin/layout/footer.blade.php
<div class="kt-footer  kt-grid__item kt-grid kt-grid--desktop kt-grid--ver-desktop" id="kt_footer">
    <div class="kt-container  kt-container--fluid ">
        <div class="kt-footer__copyright">
            {{ date('Y') }}&nbsp;&copy;&nbsp;<a href="https://wptech.net" target="_blank" class="kt-link">WP Tech</a>
        </div>
    </div>
</div>

resources/views/admin/layout/header-mobile.blade.php
<div id="kt_header_mobile" class="kt-header-mobile  kt-header-mobile--fixed ">
    <div class="kt-header-mobile__logo">
        <a href="{{ route('admin.dashboard.view') }}">
            <img alt="Logo" src="uploads/admin/logo/white-logo-sidebar.png" width="65"/>
        </a>
    </div>
    <div class="kt-header-mobile__toolbar">
        <button class="kt-header-mobile__toggler kt-header-mobile__toggler--left" id="kt_aside_mobile_toggler"><span></span></button>
        <button class="kt-header-mobile__topbar-toggler" id="kt_header_mobile_topbar_toggler"><i class="flaticon-more"></i></button>
    </div>
</div>

resources/views/admin/layout/header-topbar.blade.php
<div class="kt-header__topbar">
    <!--begin: Notifications -->
    <!--end: Quick panel toggler --><!--begin: Language bar -->
    <!--end: Language bar --><!--begin: User Bar -->


    <!--begin: User Bar -->
    <div class="kt-header__topbar-item kt-header__topbar-item--user">
        <div class="kt-header__topbar-wrapper" data-toggle="dropdown" data-offset="0px,0px">
            <div class="kt-header__topbar-user">
                <span class="kt-header__topbar-welcome kt-hidden-mobile">مرحباً بكـ ,</span>
                <span class="kt-header__topbar-username kt-hidden-mobile">{{ Auth::guard('admin')->user()->name }}</span>
                <img class="kt-hidden" alt="Pic" src="assets/admin/media/users/300_25.jpg" />
                @php
                    $name = mb_substr(Auth::guard('admin')->user()->name, 0, 1);
                @endphp
                <!--use below badge element instead the user avatar to display username's first letter(remove kt-hidden class to display it) -->
                <span class="kt-badge kt-badge--username kt-badge--unified-brand kt-badge--lg kt-badge--rounded kt-badge--bold">{{ $name }}</span>
            </div>
        </div>
        <div class="dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-anim dropdown-menu-top-unround dropdown-menu-xl">

            <!--begin: Head -->
            <div class="kt-user-card kt-user-card--skin-dark kt-notification-item-padding-x" style="background-color: #292f49;)">
{{--            <div class="kt-user-card kt-user-card--skin-dark kt-notification-item-padding-x" style="background-image: url(assets/admin/media/misc/bg-1.jpg)">--}}
                <div class="kt-user-card__avatar">
                    <img class="kt-hidden" alt="Pic" src="assets/admin/media/users/300_25.jpg" />

                    <!--use below badge element instead the user avatar to display username's first letter(remove kt-hidden class to display it) -->

                    <span class="kt-badge kt-badge--lg kt-badge--rounded kt-badge--bold kt-font-brand">{{ $name }}</span>
                </div>
                <div class="kt-user-card__name">
                    مرحباً بكـ , {{ Auth::guard('admin')->user()->name }}
                </div>
            </div>

            <!--end: Head -->

            <!--begin: Navigation -->
            <div class="kt-notification">
                <a href="{{ route('admin.dashboard.profile') }}" class="kt-notification__item">
                    <div class="kt-notification__item-icon">
                        <i class="flaticon2-calendar-3 kt-font-success"></i>
                    </div>
                    <div class="kt-notification__item-details">
                        <div class="kt-notification__item-title kt-font-bold">
                            البروفايل
                        </div>
                        <div class="kt-notification__item-time">
                            تعديل البروفايل
                        </div>
                    </div>
                </a>
                <a href="{{ route('admin.dashboard.password') }}" class="kt-notification__item">
                    <div class="kt-notification__item-icon">
                        <i class="flaticon2-lock kt-font-danger"></i>
                    </div>
                    <div class="kt-notification__item-details">
                        <div class="kt-notification__item-title kt-font-bold">
                            كلمة المرور
                        </div>
                        <div class="kt-notification__item-time">
                            تغيير كلمة المرور
                        </div>
                    </div>
                </a>
                <div class="kt-notification__custom kt-space-between">
                    <a href="{{ route('admin.dashboard.logout') }}" class="btn btn-label btn-label-brand btn-sm btn-bold">تسجيل الخروج</a>
                </div>
            </div>

            <!--end: Navigation -->
        </div>
    </div>

    <!--end: User Bar -->
</div>

resources/views/admin/layout/header.blade.php
<div id="kt_header" class="kt-header kt-grid__item  kt-header--fixed ">

<!-- begin:: Header Menu -->
@include("admin.layout.header-menu")


<!-- end:: Header Menu -->

    <!-- begin:: Header Topbar -->
@include("admin.layout.header-topbar")

<!-- end:: Header Topbar -->
</div>

resources/views/admin/layout/sub_delete.blade.php
<div class="modal fade" id="sub_confirm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title m--font-danger" id="exampleModalLabel">
                    {{ trans('delete.caution') }}!
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">
                        &times;
                    </span>
                </button>
            </div>
            <div class="modal-body">
                <h5>
                    {{ trans('delete.message') }}
                </h5>
                <p class="m--font-danger">
                    <strong>{{ trans('delete.note') }},</strong>
                    {{ trans('delete.noteDescription') }}
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    {{ trans('delete.close') }}
                </button>
                <button href="" data-dismiss="modal" aria-hidden="true" class="btn btn-danger sub_delete">
                    {{ trans('delete.yes') }}, ..
                </button>
                <input type="hidden" id="sub_delete_id">
            </div>
        </div>
    </div>
</div>